DROP TABLE IF EXISTS COLEGIO;
CREATE TABLE COLEGIO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS ESTUDIANTE; 
CREATE TABLE ESTUDIANTE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS CURSO;
CREATE TABLE CURSO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  grado INT NOT NULL,
  salon VARCHAR(250) NOT NULL,
  colegio_id INT NOT NULL,
  FOREIGN KEY(colegio_id) REFERENCES COLEGIO
);

DROP TABLE IF EXISTS PROFESOR;
CREATE TABLE PROFESOR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL  
);

DROP TABLE IF EXISTS ASIGNATURA;
CREATE TABLE ASIGNATURA (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  profesor_id INT NOT NULL,
  curso_id INT NOT NULL,
  FOREIGN KEY(profesor_id) REFERENCES PROFESOR,
  FOREIGN KEY(curso_id) REFERENCES CURSO  
);

DROP TABLE IF EXISTS ASIGNATURA_ESTUDIANTE;
CREATE TABLE ASIGNATURA_ESTUDIANTE (
  asignatura_id INT NOT NULL,
  estudiante_id INT NOT NULL,
  FOREIGN KEY(asignatura_id) REFERENCES ASIGNATURA,
  FOREIGN KEY(estudiante_id) REFERENCES ESTUDIANTE  
);

